services:
  - type: web
    name: quizchat-magic
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_URL
        value: https://backend-qvzn.onrender.com/api
      - key: NODE_ENV
        value: production 