services:
  - type: web
    name: quizapp-backend
    env: python
    buildCommand: |
      poetry install --no-interaction --no-ansi
      poetry run python manage.py collectstatic --no-input
      poetry run python manage.py migrate
    startCommand: gunicorn quizapp.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: GOOGLE_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: mcqsbank-1.onrender.com,mcqsbank-2.onrender.com,mcqsbank-3.onrender.com,localhost,127.0.0.1 
